#!/bin/bash
make -f - "$@" <<'EOF'

#Global variables
procEdgeLength:=0.5
meshEdgeLength:=0.5
numHarmonics:=400
minWavelength:=10
radialUncertainty:=0.1
inletUncertainty:=0.1
numSurfaceSamples:=0
numInletSamples:=0


#Working directory and target names
dir:=.
raw:=$(dir)/rawSurface.stl
inletVectors:=$(dir)/inletVectors.npy
clipped:=$(dir)/clipped.stl
surfaceDataDir:=$(dir)/surfaceData
harmonics:=$(surfaceDataDir)/harmonics.hdf5
skeletonEdges:=$(surfaceDataDir)/skeletonEdges.hdf5
skeletonMesh:=$(surfaceDataDir)/skeletonMesh.stl
radialVectors:=$(surfaceDataDir)/radialVectors.hdf5
surfaceSampleDir:=$(dir)/surfaceSamples
surfaceSample:=$(surfaceSampleDir)/lambda$(minWavelength)sigma$(radialUncertainty)_%g.stl
surfaceSamples:=$(shell seq -f"$(surfaceSample)" 0 $(numSurfaceSamples))
volumeMeshDir:=$(dir)/volumeMeshes
volumeMesh:=$(volumeMeshDir)/lambda$(minWavelength)sigma$(radialUncertainty)_%g.msh
volumeMeshes:=$(shell seq -f"$(volumeMesh)" 0 $(numSurfaceSamples))
inletMeshDir:=$(dir)/inletMeshes
inletMesh:=$(inletMeshDir)/lambda$(minWavelength)sigma$(radialUncertainty)_%g.stl
inletMeshes:=$(shell seq -f"$(inletMesh)" 0 $(numSurfaceSamples))
inletProfileDir:=$(dir)/inletProfiles
inletProfile:=$(inletProfileDir)/lambda$(minWavelength)sigma$(radialUncertainty)_%gsigma$(inletUncertainty)_$(numInletSamples).zip
inletProfiles:=$(shell seq -f"$(inletProfile)" 0 $(numSurfaceSamples))


#Recipes
all: $(inletProfiles) $(inletMeshes) $(volumeMeshes)

$(inletProfileDir)/%sigma$(inletUncertainty)_$(numInletSamples).zip: $(inletMeshDir)/%.stl $(inletVectors)
	mkdir $(inletProfileDir)
	julia julia/inletSamples.jl $^ $@ $(inletUncertainty) $(numInletSamples)

$(inletMeshDir)/%.stl $(volumeMeshDir)/%.msh &: $(surfaceSampleDir)/%.stl $(inletVectors)
	mkdir $(inletMeshDir)
	mkdir $(volumeMeshDir)
	vmtkpy python-vmtk/numericalMesh.py $^ $(volumeMeshDir)/$*.msh $(inletMeshDir)/$*.stl $(meshEdgeLength)

$(surfaceSamples) &: $(clipped) $(radialVectors) $(harmonics)
	mkdir $(surfaceSampleDir)
	julia julia/surfaceSamples.jl $^ $(surfaceSample) $(procEdgeLength) $(minWavelength) $(radialUncertainty) $(numSurfaceSamples)

$(harmonics): $(clipped)
	mkdir $(surfaceDataDir)
	julia julia/surfaceHarmonics.jl $^ $@ $(numHarmonics)

$(radialVectors): $(clipped) $(skeletonMesh)
	vmtkpy python-vmtk/skeletonProjection.py $^ $@

$(skeletonMesh): $(skeletonEdges)
	julia julia/skeletonMesh.jl $^ $@ $(numHarmonics)

$(skeletonEdges): $(clipped)
	mkdir $(surfaceDataDir)
	vmtkpy python-vmtk/skeletonEdges.py $^ $@ $(shell echo "$(procEdgeLength)/3" | bc -l)

$(clipped): $(raw) $(inletVectors)
	vmtkpy python-vmtk/clipInletRemesh.py $^ $@ $(procEdgeLength)


EOF
