#!/bin/bash
make -f - "$@" <<'EOF'


#Global variables
procEdgeLength:=1.0
meshEdgeLength:=0.5
surfaceUncertainty:=0.5
inletUncertainty:=10
numSurfaceSamples:=0
numInletSamples:=0


#Working directory and target names
dir:=.
raw:=$(dir)/rawSurface.stl
inletVectors:=$(dir)/inletVectors.npy
clipped:=$(dir)/clipped.stl
harmonics:=$(dir)/harmonics_h$(procEdgeLength).hdf5
surfaceSampleDir:=$(dir)/surfaceSamples
surfaceSample:=$(surfaceSampleDir)/h$(procEdgeLength)_sigma$(surfaceUncertainty)_%g.stl
surfaceSamples:=$(shell seq -f"$(surfaceSample)" 0 $(numSurfaceSamples))
volumeMeshDir:=$(dir)/volumeMeshes
volumeMesh:=$(volumeMeshDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)_%g.msh
volumeMeshes:=$(shell seq -f"$(volumeMesh)" 0 $(numSurfaceSamples))
inletMeshDir:=$(dir)/inletMeshes
inletMesh:=$(inletMeshDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)_%g.stl
inletMeshes:=$(shell seq -f"$(inletMesh)" 0 $(numSurfaceSamples))
inletProfileDir:=$(dir)/inletProfiles
inletProfile:=$(inletProfileDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)-$(inletUncertainty)_%g.zip
inletProfiles:=$(shell seq -f"$(inletProfile)" 0 $(numSurfaceSamples))


#Recipes
all: $(inletProfiles) $(inletMeshes) $(volumeMeshes)

$(inletProfileDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)-$(inletUncertainty)_%.zip: $(inletMeshDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)_%.stl $(inletVectors)
	mkdir -p $(inletProfileDir)
	julia julia/inletSamples.jl $^ $@ $(inletUncertainty) $(numInletSamples)

$(volumeMeshDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)_%.msh $(inletMeshDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)_%.stl &: $(surfaceSampleDir)/h$(procEdgeLength)_sigma$(surfaceUncertainty)_%.stl $(inletVectors)
	mkdir -p $(inletMeshDir)
	mkdir -p $(volumeMeshDir)
	vmtkpy python-vmtk/numericalMesh.py $^ $(volumeMeshDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)_$*.msh $(inletMeshDir)/h$(procEdgeLength)-$(meshEdgeLength)_sigma$(surfaceUncertainty)_$*.stl $(meshEdgeLength)

$(surfaceSamples) &: $(clipped) $(harmonics)
	mkdir -p $(surfaceSampleDir)
	julia julia/surfaceSamples.jl $^ $(surfaceSample) $(procEdgeLength) $(surfaceUncertainty) $(numSurfaceSamples)

$(harmonics): $(clipped)
	julia julia/surfaceHarmonics.jl $^ $@

$(clipped): $(raw) $(inletVectors)
	vmtkpy python-vmtk/clipInletRemesh.py $^ $@ $(procEdgeLength)


EOF
